kitajima2910/plant-store

app/Http/Controllers/HomeController.php, app/Http/Controllers/LoginController.php, app/Http/Kernel.php, app/Http/Middleware/Authenticate.php, app/Http/Middleware/RevalidateBackHistory.php, app/Http/Requests/AdminFormLogin.php, app/Providers/RouteServiceProvider.php, resources/views/pages/admin/index.blade.php, resources/views/pages/admin/login.blade.php, routes/web.php
=> midleware authenticate

app/Http/Controllers/ProductController.php, app/Product.php, resources/views/includes/admin/sidebar.blade.php
add icon for sidebar can fix  gues index
=> add icon for sidebar can fix  gues index

app/Category.php, app/Components/CategoryRecursive.php, app/Http/Controllers/CategoryController.php, database/seeds/CategorySeeder.php, resources/views/pages/admin/categories/add.blade.php, routes/web.php
=> CategoryRecursive

database/migrations/2020_07_13_111810_create_categories_table.php, database/migrations/2020_07_13_112604_create_products_table.php, routes/web.php
=> fix migrate

app/Category.php, app/Components/CategoryRecursive.php, app/Http/Controllers/CategoryController.php, app/Http/Requests/AdminFromCategory.php, database/migrations/2020_07_13_111810_create_categories_table.php, resources/views/includes/admin/footer.blade.php, resources/views/includes/admin/sidebar.blade.php, resources/views/pages/admin/categories/edit.blade.php, resources/views/pages/admin/categories/index.blade.php, resources/views/pages/admin/categories/recover.blade.php, routes/web.php
recover and create at categories
=> recover and create at categories

app/Components/CategoryRecursive.php, app/Http/Controllers/CategoryController.php, resources/views/pages/admin/categories/edit.blade.php, resources/views/pages/admin/categories/recover.blade.php, routes/web.php
categories function adminEnable, adminUpdate, fix CategoryRecursive
=> categories function adminEnable, adminUpdate, fix CategoryRecursive

app/Components/MenuRecursive.php, app/Http/Controllers/MenuController.php, app/Http/Requests/AdminFormMenu.php, app/Menu.php, database/migrations/2020_07_15_024749_create_menus_table.php, database/seeds/DatabaseSeeder.php, database/seeds/MenuSeeder.php, resources/views/pages/admin/menu/edit.blade.php, resources/views/pages/admin/menu/index.blade.php, resources/views/pages/admin/menu/recover.blade.php, routes/web.php
=> code Menu admin

resources/views/includes/guest/manage-menuchild.blade.php, resources/views/layouts/guest/master.blade.php
=> fix menu to hover

app/View/Components/ConfirmDelete.php, resources/views/components/confirm-delete.blade.php, resources/views/pages/admin/categories/index.blade.php, resources/views/pages/admin/menus/index.blade.php
=> add modal delete

app/Http/Controllers/Admin/UserController.php, app/Http/Requests/AdminFormUser.php, resources/views/pages/admin/users/create.blade.php, resources/views/pages/admin/users/edit.blade.php, resources/views/pages/admin/users/index.blade.php
=> fix User and add modal delete

app/Http/Controllers/Admin/AdminController.php, app/Http/Controllers/Admin/UserController.php, app/Http/Requests/AdminFormUser.php, resources/views/pages/admin/users/edit.blade.php
=> fix password user

resources/views/layouts/guest/master.blade.php
=> fix template

database/seeds/MenuSeeder.php
=> fix menuseeder

app/Http/Controllers/Admin/ProductController.php, app/Product.php, resources/views/pages/admin/products/index.blade.php
=> add function destroy products

app/Http/Controllers/Admin/ProductController.php
=> fix productcontroller

app/Http/Controllers/Admin/SliderController.php, app/Http/Controllers/HomeController.php, database/seeds/ProductSeeder.php, database/seeds/SliderSeeder.php, resources/views/includes/guest/hero.blade.php, resources/views/includes/guest/product.blade.php, resources/views/pages/guest/shop-details.blade.php
show slider show product saleoff hide arrow input
=> show slider show product saleoff hide arrow input

app/Http/Controllers/CartController.php, app/Providers/AppServiceProvider.php, public/frontend/css/style.css, resources/views/ajax/guest/cart-table.blade.php, resources/views/includes/guest/footer.blade.php, resources/views/includes/guest/related-product.blade.php, resources/views/pages/guest/cart.blade.php, resources/views/pages/guest/shop-details.blade.php, routes/web.php
=> update ajax cart

app/Http/Controllers/LoginController.php, app/Http/Controllers/LogoutController.php, routes/web.php
=> fix logout

app/Http/Controllers/ProductController.php, resources/views/ajax/guest/product-view.blade.php, resources/views/pages/guest/shop.blade.php, routes/web.php
=> show product

resources/views/includes/guest/blog.blade.php
=> fix  blog index

app/Category.php, app/Http/Controllers/PostController.php, app/Menu.php, database/seeds/UserSeeder.php, resources/views/includes/guest/blog.blade.php, resources/views/pages/guest/post.blade.php
=> fix sub menu, cate

app/Http/Controllers/PostController.php, app/Http/Controllers/ProductController.php, app/Providers/AppServiceProvider.php, public/vendors/shop/style.css, resources/views/ajax/guest/post-data.blade.php, resources/views/ajax/guest/product-data.blade.php, resources/views/includes/guest/category.blade.php, resources/views/includes/guest/manage-category-child.blade.php, resources/views/pages/guest/post-details.blade.php, resources/views/pages/guest/post.blade.php, resources/views/pages/guest/shop.blade.php, routes/web.php
=> ajax post and product

database/seeds/DatabaseSeeder.php, database/seeds/OrderDetailSeeder.php, database/seeds/OrderSeeder.php, database/seeds/UserSeeder.php
=> order orderdetail seed

app/Http/Controllers/HomeController.php, app/Http/Controllers/ProductController.php, resources/views/includes/guest/header.blade.php, routes/web.php
=> search products

resources/views/pages/guest/shop.blade.php
=> fix bug shop

resources/views/ajax/guest/product-data.blade.php, resources/views/includes/guest/product.blade.php
=> fix conflict

app/Providers/AppServiceProvider.php, resources/views/pages/guest/post-details.blade.php, resources/views/pages/guest/post.blade.php, resources/views/pages/guest/shop.blade.php, routes/web.php
=> add bestseller

public/frontend/css/style.css, resources/views/includes/guest/product.blade.php, resources/views/pages/guest/index.blade.php, resources/views/pages/guest/post-details.blade.php, resources/views/pages/guest/post.blade.php, resources/views/pages/guest/shop.blade.php
=> fix comparision

resources/views/includes/guest/product.blade.php, resources/views/pages/guest/shop.blade.php
=> fix compare

resources/views/includes/guest/product.blade.php, resources/views/pages/guest/index.blade.php, resources/views/pages/guest/post-details.blade.php, resources/views/pages/guest/post.blade.php, resources/views/pages/guest/shop.blade.php
=> fix format price

resources/views/includes/guest/product.blade.php, resources/views/pages/guest/shop-details.blade.php, resources/views/pages/guest/shop.blade.php
=> format comparision code

app/Http/Controllers/Admin/HomeController.php, database/seeds/ProductSeeder.php, database/seeds/UserSeeder.php, public/backend/css/style.css, resources/views/pages/admin/index.blade.php, resources/views/pages/admin/sliders/index.blade.php, resources/views/pdf/orderdetails.blade.php
=> add chart dashboard

app/Http/Controllers/ContactController.php, app/Http/Requests/GuestFormContact.php, resources/views/pages/guest/contact.blade.php, resources/views/pages/guest/email-contact.blade.php, routes/web.php
=> up contact

app/Http/Controllers/ProductController.php, app/Rating.php, database/migrations/2020_08_10_092213_create_ratings_table.php, public/vendors/shop-details/rating.js, resources/views/ajax/guest/rating-data.blade.php, resources/views/includes/guest/related-product.blade.php, resources/views/pages/guest/shop-details.blade.php, routes/web.php
=> ratings for products

app/Http/Controllers/HomeController.php, app/Http/Controllers/ProductController.php, app/Providers/AppServiceProvider.php, resources/views/ajax/admin/order-data.blade.php, resources/views/pdf/orderdetails.blade.php
=> fix code star, print pdf

app/Comment.php, app/Components/CommentRecursive.php, app/Http/Controllers/Admin/CommentController.php, config/menu.php, resources/views/pages/admin/comments/index.blade.php, resources/views/pages/guest/contact.blade.php, routes/web.php
=> up post admin

app/Http/Controllers/CartController.php, app/Http/Controllers/CheckoutController.php, app/Http/Controllers/LoginController.php, app/Http/Controllers/RegisterController.php, app/Http/Requests/GuestFormCheckout.php, app/Http/Requests/GuestFormContact.php, app/Http/Requests/GuestFormRegister.php, app/Http/Requests/GuestFormShop.php, database/seeds/UserSeeder.php, public/vendors/shop-details/rating.js, resources/views/ajax/guest/cart-table.blade.php, resources/views/ajax/guest/wishlist-data.blade.php, resources/views/pages/guest/cart.blade.php, resources/views/pages/guest/contact.blade.php, resources/views/pages/guest/post-details.blade.php, resources/views/pages/guest/post.blade.php, resources/views/pages/guest/shop-details.blade.php, resources/views/pages/guest/shop.blade.php, resources/views/pages/guest/wishlist.blade.php
=> fix code guest

app/Http/Controllers/Admin/AdminController.php, app/Http/Controllers/Admin/UserController.php, app/Http/Controllers/ContactController.php, app/Http/Controllers/RegisterController.php, app/Http/Requests/AdminFormUser.php, resources/views/includes/guest/manage-category-child.blade.php, resources/views/pages/guest/login.blade.php
=> fix code admin

resources/views/pdf/orderdetails.blade.php
=> fix code pdf

app/Http/Kernel.php, composer.lock, public/frontend/css/errors.css, resources/views/errors/404.blade.php
=> Final test

app/Http/Kernel.php, resources/views/errors/404.blade.php
=> Fix 404 page

app/Http/Controllers/Admin/ProductController.php, app/Http/Requests/AdminFormUser.php, app/Http/Requests/GuestFormRegister.php, resources/views/pages/admin/products/index.blade.php, resources/views/pages/admin/users/create.blade.php, resources/views/pages/guest/contact.blade.php, resources/views/pages/guest/register.blade.php, resources/views/pdf/product.blade.php, routes/web.php
fix confirm password and category product pdf
=> fix confirm password and category product pdf

app/Http/Controllers/SocialController.php, resources/views/pages/guest/login.blade.php
=> unique email fb

resources/views/ajax/admin/order-data.blade.php, resources/views/pages/admin/orders/index.blade.php
=> fix order delete

app/Providers/AppServiceProvider.php
=> fix code settings

app/Http/Controllers/Admin/UserController.php, app/Http/Requests/AdminFormUserEdit.php
=> fix edit user

README.md, app/Http/Controllers/HomeController.php
=> end project
